# Generated by Django 5.0.4 on 2024-05-16 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0002_customer_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='emailaddresss',
            new_name='emailaddress',
        ),
    ]
