# Generated by Django 5.0.4 on 2024-05-16 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0003_rename_emailaddresss_customer_emailaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='emailaddress',
            new_name='emailaddresss',
        ),
    ]
