# Generated by Django 5.0.4 on 2024-05-16 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0004_rename_emailaddress_enquiry_emailaddresss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='emailaddresss',
            new_name='emailaddress',
        ),
    ]
